### ISSUE TITLE
Does not compile on OSX - conda recipe

### ISSUE THREAD

**Issue by Juke34** [TravisWheelerLab/NINJA#27]
I tried to make a Conda recipe, it compiles well on Linux, but I got into trouble on OSX, see here: [https://github.com/bioconda/bioconda-recipes/pull/20135](https://github.com/bioconda/bioconda-recipes/pull/20135) and here [https://circleci.com/gh/bioconda/bioconda-recipes/93537?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link](https://circleci.com/gh/bioconda/bioconda-recipes/93537?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

Could you help?

**Comment by jebrosen** [comment]
@glesica Is there a plan/policy for macOS support? OpenMP makes things a bit tricky because the compiler that comes with macOS does not support it - you have to get a compiler via brew, conda, etc.

If the only other barrier is `clock_gettime` and related functions, it should be fairly easy to fix and I am looking into it now.

**Comment by Juke34** [comment]
Tools using OpenMP compile on OSX with conda.  We use `llvm-openmp` for it.

**Comment by glesica** [comment]
I'm able to build it with GCC on a Mac. Installing OMP manually would be a another great option. We'll take a look at this before we do the 1.0.0 release.

**Comment by jebrosen** [comment]
It's easy to remove `clock_gettime`: https://github.com/TravisWheelerLab/NINJA/compare/cluster...jebrosen:cluster-no-gettime

It only appears in two places, neither important: `TreeBuilderManager.cpp` in the develop and cluster branches only - not in the avx branch - and not used by default anyway, and in `ClusterManager.cpp` where values are calculated but not used.

**Comment by Juke34** [comment]
Did you have time to work on it?

**Comment by traviswheeler** [comment]
Apologies for the slow response on this. We've been clearing the decks on other projects, and are now turning some attention to this. Hard to give any exact timeline, but expect to see movement here shortly.
