### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by caonetto** [TravisWheelerLab/NINJA#41]
Any ideas what could be going on?
`(repeatmodeler) cris@AWRIBIO02:/mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/work/installers/NINJA-0.98-cluster_only/NINJA$ make all
g++  -std=gnu++11 -Wall -mssse3 -fopenmp -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/miniconda3/envs/funannotate/include  -c -o ArgumentHandler.o ArgumentHandler.cpp
In file included from /mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/miniconda3/envs/funannotate/include/assert.h:5,
                 from ExceptionHandler.hpp:8,
                 from ArgumentHandler.hpp:4,
                 from ArgumentHandler.cpp:7:
/mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/miniconda3/envs/funannotate/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’
   15 | typedef struct Except_Frame_T *Except_Frame_T;
      |                                ^~~~~~~~~~~~~~
/mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/miniconda3/envs/funannotate/include/except.h:15:16: note: previous declaration as ‘struct Except_Frame_T’
   15 | typedef struct Except_Frame_T *Except_Frame_T;
      |                ^~~~~~~~~~~~~~
/mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/miniconda3/envs/funannotate/include/except.h:17:18: error: field ‘prev’ has incomplete type ‘Except_Frame_T’
   17 |   Except_Frame_T prev;
      |                  ^~~~
/mnt/e70c0819-464b-4569-bbb6-cbc208b1daa1/cris/miniconda3/envs/funannotate/include/except.h:16:8: note: definition of ‘struct Except_Frame_T’ is not complete until the closing brace
   16 | struct Except_Frame_T {
      |        ^~~~~~~~~~~~~~
make: *** [<builtin>: ArgumentHandler.o] Error 1
`

**Comment by jebrosen** [comment]
Something you have installed through conda has provided a header file named `assert.h` or `except.h`, which has the same name but different contents from a system header file (the real `assert.h` should not reference an `except.h`). Conda has apparently configured the C++ compiler to treat the conda `include/` directory as one of the "system directories".

This appears to have negatively affected several other projects as well. This should be reported to whatever project provides its own conflicting `assert.h` if we can figure out what that is, and/or to conda.

To solve this issue I would first try compiling NINJA in a fresh environment, or outside of conda entirely.

**Comment by caonetto** [comment]
Thanks for that, it compiled when running it outside conda environment.

CHeers.
