### ISSUE TITLE
NINJA with large number of leaves

### ISSUE THREAD

**Issue by elichienxD** [TravisWheelerLab/NINJA#42]
Hi @traviswheeler ,

Sorry that I'm not sure whether it is suitable to ask this question here or not. I'm now using the code (ver 1.2.2) from your [website](http://wheelerlab.org/software/ninja/). Thanks for the well organized code so that even for a non-C programmer like me can work with it (my primary language is Python as I work in ML). 

I find it works okay if the number of leaves is smaller than 1000 but fail to even output a (meaningful) newick file for large dataset (say 10k leaves). I'm using the distance input option `./ninja --in_type d distance_file > tree.newick`. I didn't get any error messages. The only thing that I observe is that NINJA create an empty temp folder and output an empty newick file. Would you mind to fix this problem (or let me know how to fix it easily as a non-C programmer...)?

Thanks,
Eli

**Comment by traviswheeler** [comment]
Hi Eli.  Maybe worth a quick side note that the 1.2.2 version that you're using is a previous version written in Java, and isn't captured in this repo. Not really central to your observed error, but true all the same. 

As for your error: that version of NINJA has been successfully run on a lot of inputs of 10k+ or larger, so I won't be able to test around the error that you're experiencing without some sample data. Questions: 
- how did you compute the distance_file (what tool did you use, and what was the input to that tool)?
- can you provide the distance_file?  If you don't have another way, you might try loading it to osf.io.

**Comment by elichienxD** [comment]
Hi @traviswheeler ,

I just found that it is the problem of my input file. After fixing that bug I'm able to run NINJA successfully. I'm also quite surprise by the speed of NINJA! Thanks again for your response and your great method.

Best regards,
Eli
