### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: 10000

### ISSUE THREAD

**Issue by J-Calvelo** [TravisWheelerLab/NINJA#43]
Hello. I'm having issues running Ninja with some alignments with the following error:

```
error building tree
10000
java.lang.ArrayIndexOutOfBoundsException: 10000
        at com.traviswheeler.ninja.SequenceFileReader.<init>(SequenceFileReader.java:93)
        at com.traviswheeler.ninja.TreeBuilderManager.doJob(TreeBuilderManager.java:170)
        at com.traviswheeler.ninja.Ninja.main(Ninja.java:68)
Tree string not generated for some unknown reason. Aborting.
```
What is the source of it? I'm ataching one of the files.
Thanks

[N0.HOG0005632_work_cds.txt](https://github.com/TravisWheelerLab/NINJA/files/10550549/N0.HOG0005632_work_cds.txt)

**Comment by traviswheeler** [comment]
I suppose you must be using the Java version found at https://wheelerlab.org/software/ninja/.  Sadly, that implementation had a limit on the length of the MSA: 10,000 characters long.  We haven't fixed the problem in the Java version.  (And this C-version captured in this repo is slightly buggy, awaiting a bit more care) sorry
