### ISSUE TITLE
Is this program considering supporting the aarch64 architecture?

### ISSUE THREAD

**Issue by z4668640** [TravisWheelerLab/NINJA#44]
As the title shows, I now need to run it on an ARM chip. How can I compile it successfully?
![image](https://github.com/TravisWheelerLab/NINJA/assets/71266093/745503f1-ca7f-483d-90dc-382b4f881f08)
![image](https://github.com/TravisWheelerLab/NINJA/assets/71266093/02102f58-dc9b-400d-aaf8-146b3a01c9bb)

**Comment by traviswheeler** [comment]
Thanks for your interest in this implementation of NINJA. This repository is an "almost complete" reimplementation of the Java implementation at [this site](https://wheelerlab.org/software/ninja/). The software generally works, but there remain a couple of small bugs, and the project is on hold (and not under active development) while we await the time to wrap it up to completion. For now, your best bet is probably to use the Java version listed in the previous sentence.

I'll leave this issue open, since this is a feature we'd like to support when we wrap things up

**Comment by z4668640** [comment]
> Thanks for your interest in this implementation of NINJA. This repository is an "almost complete" reimplementation of the Java implementation at [this site](https://wheelerlab.org/software/ninja/). The software generally works, but there remain a couple of small bugs, and the project is on hold (and not under active development) while we await the time to wrap it up to completion. For now, your best bet is probably to use the Java version listed in the previous sentence.
> 
> I'll leave this issue open, since this is a feature we'd like to support when we wrap things up

Thank you for your reply, but I'm afraid not. Since your software is a dependency on another software, I expect this to be difficult to migrate. https://github.com/Dfam-consortium/RepeatModeler

**Comment by traviswheeler** [comment]
Ah, yes. For that dependency, the specific release (0.98-cluster_only) of NINJA *is* the right one.

Have you tried compiling under Rosetta (https://support.apple.com/en-us/HT211861)?

**Comment by z4668640** [comment]
> Ah, yes. For that dependency, the specific release (0.98-cluster_only) of NINJA _is_ the right one.
> 
> Have you tried compiling under Rosetta (https://support.apple.com/en-us/HT211861)?

No, I'm not using an apple. I use a Linux system. I'll look into the problem myself first. Thank you.

**Comment by z4668640** [comment]
> Ah, yes. For that dependency, the specific release (0.98-cluster_only) of NINJA _is_ the right one.
> 
> Have you tried compiling under Rosetta (https://support.apple.com/en-us/HT211861)?

I may have found a solution to this problem.
1. First we need to remove the "-mssse3" parameter from line 36 of the Makefile
2. Second, we need to replace lines 8, 9, and 10 of the distancecalculater.hpp file with the following
```
#include <xmmintrin.h>        /* SSE  */
#include <emmintrin.h>        /* SSE2 */
#include <tmmintrin.h>      /* SSE3 */
```
replace with
`#include "sse2neon.h"`
3. Third, download the sse2neon.h file from this address and place it in the same directory as the DistanceCalculator.hpp file.
sse2neon.h The download address is as follows:
https://github.com/DLTcollab/sse2neon/blob/master/sse2neon.h

**Comment by z4668640** [comment]
I refer to the Intel's official description: https://github.com/DLTcollab/sse2neon

**Comment by martin-g** [comment]
I've opened a PR that makes the changes suggested by @z4668640 at https://github.com/TravisWheelerLab/NINJA/issues/44#issuecomment-1865781967

**Comment by z4668640** [comment]
> I've opened a PR that makes the changes suggested by @z4668640 at [#44 (comment)](https://github.com/TravisWheelerLab/NINJA/issues/44#issuecomment-1865781967)

Thank you very much for your help. But I must warn you that my method is only one possibility. He hasn't been rigorously tested.

**Comment by martin-g** [comment]
I have used this solution in several other projects and it worked well!

I also added a CI job that runs `make check` on Linux ARM64!
