### ISSUE TITLE
Download links for 0.99-cluster_only point to a different version of NINJA

### ISSUE THREAD

**Issue by rpm78** [TravisWheelerLab/NINJA#46]
**Describe the bug**
Download links for 0.99-cluster_only point to an older non-cluster version of NINJA.

**To Reproduce**
```
curl -sSLO "https://github.com/TravisWheelerLab/NINJA/archive/refs/tags/0.99-cluster_only.tar.gz"
tar -xvzf 0.99-cluster_only.tar.gz
cd NINJA-0.99-cluster_only
make build 
cd NINJA/
./Ninja --version
```
Returns "0.95".

**Expected behavior**
```./Ninja --version```
should return something like "0.99-cluster_only".

**Host system:**
`Linux ..... 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

`No LSB modules are available.
Distributor ID: Linuxmint
Description: Linux Mint 21.1
Release:	21.1
Codename:  vera`

**Comment by rmhubley** [comment]
Sorry this version of Ninja was not created from the "cluster" branch and therefore is not compatible with RepeatModeler.  I have generated a new version Ninja-1.00-cluster_only that should work, and as a bonus reports the correct version number when using the "-v" option.
